// Turns keys/debug.keystore into the forms the two apps read, since neither Windows' CNG nor
// the browser's WebCrypto can open a JKS keystore:
//
//   desktop/res/debug.pk8   the private key (PKCS #8, DER)
//   desktop/res/debug.cer   the certificate (DER)
//   web/debug-key.js        both, base64-encoded
//
// Usage (from the repository root):  java tools/ExtractKey.java [alias] [password]

import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.Key;
import java.security.KeyStore;
import java.util.Base64;

public class ExtractKey {
    public static void main(String[] args) throws Exception {
        String alias = args.length > 0 ? args[0] : "androiddebugkey";
        char[] password = (args.length > 1 ? args[1] : "android").toCharArray();

        KeyStore store = KeyStore.getInstance("JKS");
        try (FileInputStream in = new FileInputStream("keys/debug.keystore")) {
            store.load(in, password);
        }
        Key key = store.getKey(alias, password);
        byte[] cert = store.getCertificate(alias).getEncoded();

        Files.write(Path.of("desktop/res/debug.pk8"), key.getEncoded());
        Files.write(Path.of("desktop/res/debug.cer"), cert);
        Base64.Encoder base64 = Base64.getEncoder();
        Files.writeString(Path.of("web/debug-key.js"),
                "// Generated by tools/ExtractKey.java from keys/debug.keystore. Do not edit.\n"
                + "// This is the debug key bundled with uber-apk-signer (CN=Android Debug). It is public,\n"
                + "// so shipping it in a web page gives nothing away.\n"
                + "export const PRIVATE_KEY_PKCS8 = \"" + base64.encodeToString(key.getEncoded()) + "\";\n"
                + "export const CERTIFICATE = \"" + base64.encodeToString(cert) + "\";\n");
        System.out.println("wrote desktop/res/debug.pk8, desktop/res/debug.cer and web/debug-key.js ("
                + key.getFormat() + " key, " + cert.length + "-byte certificate)");
    }
}
